{
    "name": "Smart Form Builder (Standalone)",
    "version": "18.0.1.4.0",
    "category": "Tools",
    "summary": "Standalone form builder with dynamic DB dropdown options",
    "author": "Verinsure",
    "website": "https://verinsure.com",
    "license": "LGPL-3",
    "depends": ["base", "base_setup", "website"],
    "data": [
        "security/ir.model.access.csv",
        "views/actions.xml",
        "views/menu.xml",
        "views/form_views.xml",
        "views/field_views.xml",
        "views/submission_views.xml",
        "views/branch_rule_views.xml",
        "views/select_field_wizard_views.xml",
        "views/logic_rule_views.xml",
        "views/settings_views.xml",
        "views/templates.xml",
    ],
    "assets": {
        "web.assets_frontend": [
            "smart_form_builder/static/src/css/sfb_dropdown.css",
            "smart_form_builder/static/src/css/sfb_form.css",
            "smart_form_builder/static/src/js/dynamic_options.js",
            "smart_form_builder/static/src/js/branching.js",
            "smart_form_builder/static/src/js/smart_form_frontend.js",
        ],
    },
    "images": [
        "static/description/banner.png",
        "static/description/screenshot_01.png",
        "static/description/screenshot_02.png",
        "static/description/screenshot_03.png",
        "static/description/screenshot_04.png",
        "static/description/screenshot_05.png",
        "static/description/screenshot_06.png",
        "static/description/screenshot_07.png",
        "static/description/screenshot_08.png",
        "static/description/screenshot_09.png",
        "static/description/screenshot_10.png",
        "static/description/screenshot_11.png",
    ],
    "application": True,
    "installable": True,
}
